In [1]:
import numpy as np
import pandas as pd
import sklearn as sk
import matplotlib.pyplot as plt

In [2]:
game_csv = pd.read_csv('./data/Training_dataset_Original.csv',na_values=["NA", "na", "missing"])
gameDf = pd.DataFrame(game_csv)

dataDict = pd.read_csv('./data/Data_Dictionary.csv',na_values="NA")

In [3]:
dic = dict(zip(dataDict.values[:, 1], dataDict.values[:, 0]))

In [4]:
#remove ID column
del gameDf[dic['Application ID (primary key)']]
del dic['Application ID (primary key)']

In [5]:
gameX = gameDf.iloc[:,:-1]
gameY = gameDf.iloc[:,-1]

In [6]:
range(gameDf["mvar47"].shape[0])

range(0, 80000)

In [10]:
#one hot encoding C=0 L=1
gameX.loc[gameX.loc[:, "mvar47"]=='C', "mvar47"] = 0
gameX.loc[gameX.loc[:, "mvar47"]=='L', "mvar47"] = 1


In [11]:
#Missing values median
gameX.fillna(gameX.median(),inplace = True)

mvar1   mvar2   mvar3  mvar4  mvar5    mvar6     mvar7     mvar8  \
0      1696.0  1.6541   0.000  0.000  0.000      0.0    6015.0     322.0   
1      1846.0  0.8095   0.000  0.000  0.000    102.0    7532.0    3171.0   
2      1745.0  0.4001   0.000  0.000  0.000    297.0    2536.0    2478.0   
3      1739.0  0.2193   0.000  0.000  0.000   1982.0   26440.0    4955.0   
4      1787.0  0.0118   0.225  0.000  0.000   5451.0    5494.0    5494.0   
5      1579.0  0.5389   3.502  0.000  0.000    297.0    6967.0    2478.0   
6      1818.0  0.4001   0.000  0.000  0.000    297.0    1088.0    2478.0   
7      1742.0  0.5389   0.300  0.000  0.000    297.0    6967.0    2478.0   
8      1836.0  0.1358   0.000  0.000  0.000    347.0   38964.0   17828.0   
9      1839.0  0.1981   0.000  0.000  0.000    793.0    6131.0    6045.0   
10     1903.0  0.0000   0.000  0.000  0.000     22.0   19518.0    9910.0   
11     1681.0  1.5888   5.685  3.566  0.000     93.0    3554.0     439.0   
12     1841.0  0.5388   0.000  0.000  0.000   1487.0   19449.0   19449.0   
13     1794.0  1.9684   0.000  0.000  0.000    856.0    8609.0    8609.0   
14     1669.0  3.8558  18.465  6.292  1.200    297.0     142.0    2478.0   
15     1583.0  3.0284  16.325  0.000  0.000    297.0    6967.0    2478.0   
16     1899.0  0.0970   0.000  0.000  0.000   1015.0   13379.0   13379.0   
17     1690.0  8.7747  10.437  0.000  0.000    122.0     623.0     299.0   
18     1599.0  0.8601   1.525  1.525  0.000    297.0     878.0    2478.0   
19     1859.0  0.0155   0.368  0.000  0.000    424.0   86509.0   12451.0   
20     1880.0  2.6101   0.000  0.000  0.000      0.0   19252.0    6342.0   
21     1852.0  3.6201   0.000  0.000  0.000    799.0   16515.0   16515.0   
22     1655.0  3.0268  14.748  0.000  0.000     48.0      48.0      48.0   
23     1863.0  0.0401   0.000  0.000  0.000   1487.0    4955.0    4955.0   
24     1753.0  0.2251   0.000  0.000  0.000   1124.0    1124.0    1124.0   
25     1894.0  0.0318   0.000  0.000  0.000   4655.0    7433.0    7433.0   
26     1803.0  0.3993   0.000  0.000  0.000    496.0   10505.0     496.0   
27     1932.0  0.3276   0.000  0.000  0.000   6982.0   21569.0   18829.0   
28     1714.0  5.1904   0.770  0.000  0.000      0.0    1889.0     595.0   
29     1742.0  2.0457   4.514  0.000  0.000    297.0    6967.0    2478.0   
...       ...     ...     ...    ...    ...      ...       ...       ...   
79970  1834.0  1.2164   0.000  0.000  0.000   2212.0    5244.0    4203.0   
79971  1729.0  1.3696   0.000  0.000  0.000    356.0    4218.0    1982.0   
79972  1753.0  5.8283   0.000  0.000  0.000    180.0    4014.0     617.0   
79973  1748.0  1.9635   0.642  0.000  0.000    291.0    3469.0    3469.0   
79974  1771.0  1.7588   0.000  0.000  0.000     66.0   12626.0    6433.0   
79975  1766.0  0.9540   0.000  0.000  0.000   1140.0   10207.0   10207.0   
79976  1822.0  0.0000   1.853  1.853  0.000   2581.0   13361.0    5946.0   
79977  1824.0  0.5634   0.000  0.000  0.000   3964.0    4683.0    4683.0   
79978  1914.0  0.0544   0.000  0.000  0.000   3469.0   20424.0   20424.0   
79979  1600.0  2.6649  18.282  1.078  2.678      0.0    7205.0       0.0   
79980  1822.0  0.5851   0.000  0.000  0.000      0.0   23685.0   23685.0   
79981  1693.0  0.1828  17.767  2.024  0.000    114.0   27514.0     384.0   
79982  1735.0  3.1701   0.260  0.000  0.000    117.0     892.0     117.0   
79983  1671.0  0.1380   0.000  0.000  0.000    297.0     491.0    2478.0   
79984  1924.0  0.1221   0.000  0.000  0.000   2478.0  266683.0  266683.0   
79985  1670.0  0.0347   9.836  0.000  0.000    212.0    7848.0     491.0   
79986  1901.0  0.1782   0.000  0.000  0.000   4955.0   21753.0   12673.0   
79987  1835.0  0.5372   0.000  0.000  0.000      0.0   29723.0    3964.0   
79988  1927.0  0.0410   0.000  0.000  0.000  22000.0   30046.0   24165.0   
79989  1742.0  0.1451   0.000  0.000  0.000    297.0    6967.0    2478.0   
79990  1941.0  0.4834   0.000  0.000  0.000  10846.0   5

In [65]:
def scoring(yhat0, y):
    
    y = np.array(y)
    y.sort()
    
    pointsMax = 0
    thresh=0
    
    for thresh in np.arange(0.0, 1.1, 0.1):
        points = 0
        budget = 50000
        yhat = np.array(yhat0>thresh, dtype=yhat0.dtype)
        for i in range(len(y)):
            if y[i] == 0:
                if yhat[i] == 0:
                    points+=100
                    budget-=5
                else:
                    budget-=10
            else:
                if yhat[i]==0:
                    points-=50
                    budget-=10
                else:
                    points+=100
                    budget-=10
            if budget<=0:
                break
        if pointsMax<points:
            pointsMax=points
            threshMax = thresh
            
        print(thresh, " ", points)
            
    return pointsMax, threshMax

In [90]:
from sklearn import model_selection

xtrain, xtest, ytrain, ytest = model_selection.train_test_split(gameX,gameY, test_size=0.99, stratify = gameY, random_state=1)

import time
from sklearn.grid_search import GridSearchCV
from sklearn.ensemble import GradientBoostingClassifier

cv = model_selection.StratifiedKFold(n_splits=3, shuffle=True, random_state=100)

In [109]:
#Logistic Regression
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=1, solver='lbfgs', multi_class='multinomial').fit(xtrain, ytrain)

In [110]:
clf.predict_proba(gameX).shape

(80000, 2)

In [93]:
clf.predict_proba(gameX)[0:100]

array([[ 0.51405916,  0.48594084],
       [ 0.71480307,  0.28519693],
       [ 0.63577228,  0.36422772],
       [ 0.69979237,  0.30020763],
       [ 0.74697985,  0.25302015],
       [ 0.51769212,  0.48230788],
       [ 0.67913413,  0.32086587],
       [ 0.62941999,  0.37058001],
       [ 0.84760843,  0.15239157],
       [ 0.79850653,  0.20149347],
       [ 0.81398938,  0.18601062],
       [ 0.61048076,  0.38951924],
       [ 0.85934104,  0.14065896],
       [ 0.79914875,  0.20085125],
       [ 0.47303009,  0.52696991],
       [ 0.56503799,  0.43496201],
       [ 0.74098305,  0.25901695],
       [ 0.56920756,  0.43079244],
       [ 0.62107257,  0.37892743],
       [ 0.82526089,  0.17473911],
       [ 0.86623548,  0.13376452],
       [ 0.88575879,  0.11424121],
       [ 0.50713735,  0.49286265],
       [ 0.77591432,  0.22408568],
       [ 0.6562036 ,  0.3437964 ],
       [ 0.81954375,  0.18045625],
       [ 0.64897633,  0.35102367],
       [ 0.85269962,  0.14730038],
       [ 0.5889928 ,

In [94]:
clf.predict(gameX)[:100]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1])

In [95]:
#train score
t=time.time()
print(scoring(clf.predict_proba(gameX)[:, 1], gameY))
print(time.time()-t)


0.0   0
0.1   54800
0.2   131200
0.3   249600
0.4   503100
0.5   841200
0.6   966400
0.7   994600
0.8   996800
0.9   998800
1.0   1000000
(1000000, 1.0)
0.10575985908508301


In [96]:
#test score
t=time.time()
print(scoring(clf.predict_proba(xtest)[:, 1], ytest))
print(time.time()-t)


0.0   0
0.1   52200
0.2   116300
0.3   229700
0.4   465100
0.5   812800
0.6   964200
0.7   994600
0.8   997400
0.9   998400
1.0   1000000
(1000000, 1.0)
0.0945122241973877


In [123]:
clf = LogisticRegression(random_state=1, solver='lbfgs', multi_class='multinomial').fit(gameX, gameY)

In [124]:
#Leaderboard
clf = clf

leader_csv = pd.read_csv('./data/Leaderboard_dataset.csv',na_values=["NA", "na", "missing"])
leaderDf = pd.DataFrame(leader_csv)



leaderAppID = leaderDf['application_key']
del leaderDf['application_key']



leaderX = leaderDf

In [125]:
#one hot encoding C=0 L=1
leaderX.loc[leaderX.loc[:, "mvar47"]=='C', "mvar47"] = 0
leaderX.loc[leaderX.loc[:, "mvar47"]=='L', "mvar47"] = 1


In [126]:
#Missing values median
leaderX.fillna(leaderX.mean(),inplace = True)

mvar1      mvar2   mvar3    mvar4  mvar5         mvar6         mvar7  \
0      1753.0   0.500100   0.000   0.0000  0.000    206.000000  19179.000000   
1      1894.0   1.970100   0.000   0.0000  0.000    297.000000  19820.000000   
2      1774.0   0.171800   0.000   0.0000  0.000    197.000000   2563.000000   
3      1586.0   0.112300   5.299   0.0000  0.000   1624.069192  17750.368864   
4      1832.0   1.444200   0.000   0.0000  0.000    179.000000   7577.000000   
5      1838.0   0.054400   0.241   0.0000  0.000    882.000000  14039.000000   
6      1743.0   1.075300   0.272   0.0000  0.000    397.000000  16141.000000   
7      1935.0   0.560100   0.000   0.0000  0.000    496.000000  44919.000000   
8      1885.0   0.081100   0.000   0.0000  0.000   7369.000000  19264.000000   
9      1730.0   0.744400   0.000   0.0000  0.000      0.000000   2103.000000   
10     1731.0   0.509700   0.000   0.0000  0.000   2433.000000   8673.000000   
11     1755.0   0.301300   0.000   0.0000  0.000    261.000000   4051.000000   
12     1739.0   2.290900   0.000   0.0000  0.000      0.000000   7620.000000   
13     1562.0   0.000000  34.611   3.7845  0.000   1624.069192     18.000000   
14     1798.0   5.082500   0.000   0.0000  0.000    259.000000   3359.000000   
15     1684.0   1.547900   1.338   0.0000  0.000   1624.069192  17750.368864   
16     1789.0   0.000000   1.428   0.0000  0.000   2478.000000  13874.000000   
17     1862.0   0.240100   0.000   0.0000  0.000   1487.000000  12310.000000   
18     1767.0   0.300100   1.514   0.0000  0.000    991.000000   2478.000000   
19     1802.0   0.636400   0.000   0.0000  0.000     96.000000  18759.000000   
20     1780.0   1.955900   0.000   0.0000  0.000    191.000000  12525.000000   
21     1714.0   2.266400   0.000   0.0000  0.000     31.000000   1671.000000   
22     1923.0   0.088000   0.000   0.0000  0.000   5946.000000  53893.000000   
23     1743.0   1.720800   2.295   0.0000  0.000    159.000000   3621.000000   
24     1700.0   1.660500   0.000   0.0000  0.000      0.000000   1037.000000   
25     1922.0   1.118127   0.000   0.0000  0.000   4524.000000  15530.000000   
26     1777.0   0.412000   0.000   0.0000  0.000    369.000000   6201.000000   
27     1811.0   0.911700   0.410   0.0000  0.410    297.000000  27717.000000   
28     1658.0   2.382900  37.127  10.3678  0.000      0.000000    396.000000   
29     1827.0   0.280100   0.000   0.0000  0.000    678.000000   1189.000000   
...       ...        ...     ...      ...    ...           ...           ...   
24970  1734.0   0.927900   0.520   0.0000  0.000    256.000000  11643.000000   
24971  1849.0   1.830500   0.000   0.0000  0.000   2251.000000  33275.000000   
24972  1739.0   1.525100   2.727   0.0000  2.727      8.000000   2129.000000   
24973  1642.0   0.000000   3.353   1.2114  0.000   1624.069192   6290.000000   
24974  1709.0   3.680100   7.583   3.1371  0.000    297.000000   8132.000000   
24975  1890.0   0.000000   0.000   0.0000  0.000   1982.000000  15162.000000   
24976  1727.0   1.844800  15.181   0.0000  0.000   2234.000000   2754.000000   
24977  1789.0   1.299400   0.000   0.0000  0.000    364.000000  17838.000000   
24978  1706.0   0.499700   0.000   0.0000  0.000     98.000000    297.000000   
24979  1638.0   4.680200  16.751   2.6642  0.000   1624.069192   7937.000000   
24980  1855.0   1.996500   0.000   0.0000  0.000    350.000000  30203.000000   
24981  1790.0   0.205000   0.000   0.0000  0.000    237.000000  18018.000000   
24982  1546.0   0.349100  50.803   4.2695  0.000   1624.069192  17750.368864   
24983  1777.0   3.962900   0.968   0.0000  0.000     14.000000  23707.000000   
24984  1943.0   1.118127   0.000   0.0000  0.000      0.000000  24775.000000   
24985  1691.0   0.166300   1.979   0.0000  0.000      0.000000   9591.000000   
24986  1681.0   0.173900   9.006   0.0000  6.568      0.000000   3004.000000   
24987  1723.0   1.057000   0.285   0.0000  0.000    248.000000  28479.000000   
24988  1

In [127]:
pred = clf.predict_proba(leaderX)[:, 1]
# pred.sort()
# pred = pd.DataFrame(pred)
# pred = pred.sort_values(by = 0,kind = 'mergesort',ascending = True)

pred = pd.DataFrame({'0':leaderAppID,  '1': pred })


# pred['application_key'] = leaderAppID
# pred = pred.sort_values(by = 0,kind = 'mergesort',ascending = True)

In [128]:
pred

0         1
0      350053  0.401136
1      350054  0.094113
2      350055  0.344568
3      350056  0.458551
4      350057  0.317241
5      350058  0.082752
6      350059  0.323307
7      350060  0.055476
8      350061  0.124622
9      350062  0.296980
10     350063  0.293142
11     350064  0.417423
12     350065  0.409360
13     350066  0.462091
14     350067  0.326797
15     350068  0.437167
16     350069  0.197787
17     350070  0.268847
18     350071  0.365287
19     350072  0.186444
20     350073  0.268504
21     350074  0.470182
22     350075  0.045454
23     350076  0.404091
24     350077  0.533109
25     350078  0.046130
26     350079  0.320675
27     350080  0.229499
28     350081  0.563122
29     350082  0.335238
...       ...       ...
24970  375023  0.438114
24971  375024  0.197460
24972  375025  0.513317
24973  375026  0.412606
24974  375027  0.417278
24975  375028  0.165895
24976  375029  0.346027
24977  375030  0.260412
24978  375031  0.414793
24979  375032  0.432623
24980  375033  0.011641
24981  375034  0.352694
24982  375035  0.475864
24983  375036  0.256254
24984  375037  0.072310
24985  375038  0.403310
24986  375039  0.382523
24987  375040  0.378353
24988  375041  0.456049
24989  375042  0.422605
24990  375043  0.394087
24991  375044  0.233014
24992  375045  0.447850
24993  375046  0.414480
24994  375047  0.291975
24995  375048  0.256750
24996  375049  0.137284
24997  375050  0.391379
24998  375051  0.170615
24999  375052  0.086425

[25000 rows x 2 columns]

In [129]:
pred = pred.sort_values('1')
pred

0             1
21128  371181  7.903959e-08
15911  365964  1.252205e-07
22990  373043  1.325307e-06
22465  372518  1.576880e-06
7820   357873  3.280688e-06
13848  363901  4.329826e-06
3642   353695  4.884471e-06
24868  374921  8.794918e-06
8558   358611  9.509647e-06
23607  373660  1.741171e-05
21731  371784  1.985787e-05
21040  371093  2.165037e-05
7674   357727  2.168154e-05
19140  369193  2.746675e-05
922    350975  2.963988e-05
11401  361454  3.926457e-05
14150  364203  5.160870e-05
8145   358198  7.384204e-05
22203  372256  7.947347e-05
19883  369936  1.283002e-04
20952  371005  1.643362e-04
2821   352874  1.744701e-04
18127  368180  1.774812e-04
17058  367111  2.593784e-04
16696  366749  3.621329e-04
16123  366176  5.281941e-04
22265  372318  5.442830e-04
2564   352617  5.625860e-04
13465  363518  6.786185e-04
3747   353800  7.150361e-04
...       ...           ...
23177  373230  6.705494e-01
4377   354430  6.818219e-01
20367  370420  6.859181e-01
11226  361279  6.904820e-01
12951  363004  6.918076e-01
15417  365470  6.922688e-01
3459   353512  6.930934e-01
1375   351428  6.942237e-01
19967  370020  6.942326e-01
16772  366825  6.952329e-01
14196  364249  7.001122e-01
17742  367795  7.040649e-01
17884  367937  7.047769e-01
24384  374437  7.157436e-01
22175  372228  7.157465e-01
18864  368917  7.182574e-01
13727  363780  7.207544e-01
18698  368751  7.351635e-01
18136  368189  7.394568e-01
6246   356299  7.690489e-01
3266   353319  7.813266e-01
4295   354348  7.872506e-01
12556  362609  7.917761e-01
22530  372583  7.967264e-01
3186   353239  8.278418e-01
1172   351225  8.302845e-01
4871   354924  8.410331e-01
11064  361117  8.674138e-01
20066  370119  8.877816e-01
21212  371265  9.999929e-01

[25000 rows x 2 columns]

In [130]:
np.array(pred)

array([[  3.71181000e+05,   7.90395923e-08],
       [  3.65964000e+05,   1.25220516e-07],
       [  3.73043000e+05,   1.32530740e-06],
       ..., 
       [  3.61117000e+05,   8.67413781e-01],
       [  3.70119000e+05,   8.87781570e-01],
       [  3.71265000e+05,   9.99992862e-01]])

In [131]:
thresh = 0.8
print("THRESHOLD:", thresh)
pred = np.array(pred)
pred[pred[:, 1]>thresh, 1] = 1
pred[pred[:, 1]<=thresh, 1] = 0

THRESHOLD: 0.8


In [132]:
pred

array([[  3.71181000e+05,   0.00000000e+00],
       [  3.65964000e+05,   0.00000000e+00],
       [  3.73043000e+05,   0.00000000e+00],
       ..., 
       [  3.61117000e+05,   1.00000000e+00],
       [  3.70119000e+05,   1.00000000e+00],
       [  3.71265000e+05,   1.00000000e+00]])

In [133]:
submit = pd.DataFrame(pred)[:10000]

In [137]:
submit = submit.astype('int64')

In [138]:
submit.to_csv('flabbergasted_IITGuwahati_32.csv',header = False, index = False)